export interface Search {
  searchKey?: string;
  searchFromDate?: string;
  searchToDate?: string;
  searchCloseDate?: string;
  searchKeyword?: string;
  searchState?: string;
  searchCharge?: string;
  searchAction?: string;
  searchLimit?: string;
  searchCursor?: string;
  searchDR?: string;
  searchES?: string;
  searchLR?: string;
  searchDC?: string;
  searchEC?: string;
  searchDG?: string;
  searchRR?: string;
  searchCuCode?: string;
  searchDomain?: string;
  searchChargeDefine?: string;
  searchDateType?: string;
  toDate?: string | null;
  fromDate?: string | null;
  scope?: string | null;
  catCode?: string | null;
  kind?: string | null;
  keyword?: string | null;
  userType?: string | null;
  useFlag?: string | null;
  insCode?: string | null;
  store?: string | null;
  path?: string | null;
  cursor?: string;
  limit?: number;
}
