import { QTableProps } from 'quasar';

export const SOCKET_USER_COLUMN: QTableProps['columns'] = [
  {
    name: 'userId',
    required: true,
    label: '아이디',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'store',
    required: true,
    label: '서비스',
    align: 'center',
    field: '',
    sortable: true,
    style: 'max-width: 50px',
    headerStyle: 'max-width: 50px',
  },
  {
    name: 'insCode',
    required: true,
    label: '기관코드',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 60px',
    headerStyle: 'max-width: 60px',
  },
  {
    name: 'userType',
    required: true,
    label: '접속자',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 50px',
    headerStyle: 'max-width: 50px',
  },
  {
    name: 'connected',
    required: true,
    label: '접속',
    align: 'center',
    field: '',
    sortable: true,
    style: 'max-width: 30px',
    headerStyle: 'max-width: 30px',
  },
  {
    name: 'createdAt',
    required: true,
    label: '접속일',
    align: 'center',
    field: '',
    sortable: true,
    style: 'max-width: 80px',
    headerStyle: 'max-width: 80px',
  },
];
