import { QTableProps } from 'quasar';

export const DOCUMENT_LIST_COLUMN: QTableProps['columns'] = [
  {
    name: 'index',
    label: 'No',
    field: 'index',
  },
  {
    name: 'appId',
    required: true,
    label: '앱관리번호',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 280px',
    headerStyle: 'max-width: 280px',
  },
  {
    name: 'docId',
    required: true,
    label: '전문관리번호',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 280px',
    headerStyle: 'max-width: 280px',
  },
  {
    name: 'scope',
    required: true,
    label: '전문분류',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'catCode',
    required: true,
    label: '업무구분',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'state',
    required: true,
    label: '처리상태',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'useFlag',
    required: true,
    label: '사용상태',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'store',
    required: true,
    label: '서비스',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'case_no',
    required: true,
    label: '관리번호',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'case_ref_no',
    required: true,
    label: '은행관리번호',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'insCode',
    required: true,
    label: '기관코드',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 70px',
    headerStyle: 'max-width: 70px',
  },
  {
    name: 'ownerId',
    required: true,
    label: '요청자',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'info',
    required: true,
    label: '부가정보',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'createdAt',
    required: true,
    label: '등록일시',
    align: 'center',
    field: '',
    sortable: false,
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
  },
  {
    name: 'detailButton',
    label: '-',
    field: 'detailButton',
  },
];
